camel:
  springboot:
    name: AmqArtemisAlerting
    jmx-enabled: false
    
    # keep Camel running
    main-run-controller: true
    
    # verbose summary so you can see the pairing of routes and routes configurations
    startup-summary-level: verbose

amq:
  brokers:
    -
      brokerName: artemis
      username: joe
      password: joe
      host: 192.168.0.18
      jmxrmiPort: 1099
      # active, passive
      role: active
      clustered: true
      addressesToMonitor:
        - DLQ
        - ExpiryQueue
        - TEST
    -
      brokerName: artemisB
      username: joe
      password: joe
      host: 192.168.0.18
      jmxrmiPort: 1099
      # active, passive
      role: passive
      clustered: false
      addressesToMonitor:
        - DLQ
        - ExpiryQueue
    -
      brokerName: artemisC
      username: joe
      password: joe
      host: 192.168.0.18
      jmxrmiPort: 1099
      # active, passive
      role: active
      clustered: false
      addressesToMonitor:
        - DLQ
        - ExpiryQueue

smtp:
  host: localhost
  port: 1025
  username: joe
  password: joe
  fromEmail: joe@joe.com
  contentType: text/xml
  
application:
  alert: 
    enabled: true
    period: 30000
    broker-thresholds:
      connections: 1
      totalConnections: 30
      diskStoreUsage: 0.10
      addressMemoryPercentage: 0.1
    address-thresholds:
      consumers: 0
      messageCount: 1
  summary:
    enabled: true
    period: 60000    

##webhook endpoint
#application.webhook.endpoint = https://webhook.site/3aea0c2f-8b7a-4f8c-88f8-7fce277e96af
#
#
#
##alert configs
#total.message.count.threshold = 6
#peak.thread.count.threshold = 39
#connection.count.threshold = 1000
#queue.message.count.threshold = 5
#address.memory.threshold = 0.85
#diskstore.usage.threshold = 0.9
#process.cpu.load.threshold = 1
#
##heap percentage used
#heap.memory.limit = 300000000
#broker.connection.count.threshold = 